create extension if not exists pgcrypto;

-- Configurari persistente ale aplicatiei: parola adminului si planul de studiu.
create table if not exists public.app_settings (
    key text primary key,
    value text not null,
    updated_at timestamptz not null default now()
);

-- Sesiunile aplicatiei sunt proprii backend-ului, nu Supabase Auth.
create table if not exists public.auth_sessions (
    id uuid primary key default gen_random_uuid(),
    role text not null check (role in ('admin', 'student')),
    first_name text not null default '',
    last_name text not null default '',
    display_name text not null,
    initials text not null,
    email text not null default '',
    created_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    is_active boolean not null default true
);

create index if not exists auth_sessions_active_role_last_seen_idx
    on public.auth_sessions (role, is_active, last_seen_at desc);

create index if not exists auth_sessions_display_name_lower_idx
    on public.auth_sessions (lower(trim(display_name)));

-- Continutul lectiilor si exercitiilor ramane versionat in cod. Aici se pastreaza
-- numai raspunsurile/progresul utilizatorilor.
create table if not exists public.learning_progress (
    id bigint generated by default as identity primary key,
    owner_key text not null,
    session_id uuid references public.auth_sessions(id) on delete set null,
    student_email text not null default '',
    exercise_id integer not null,
    was_correct boolean not null,
    answered_at timestamptz not null default now()
);

create index if not exists learning_progress_owner_answered_idx
    on public.learning_progress (owner_key, answered_at desc);

create index if not exists learning_progress_owner_exercise_idx
    on public.learning_progress (owner_key, exercise_id);

-- Monitorizarea publica veche (pagina Rapoarte).
create table if not exists public.tracked_students (
    id bigint generated by default as identity primary key,
    identity_key text not null unique,
    name text not null,
    class_name text not null default '',
    email text not null default '',
    created_at timestamptz not null default now()
);

alter table public.tracked_students
    add column if not exists identity_key text;

update public.tracked_students
set identity_key = encode(
    digest(
        lower(trim(name)) || chr(31) ||
        lower(trim(coalesce(class_name, ''))) || chr(31) ||
        lower(trim(coalesce(email, ''))),
        'sha256'
    ),
    'hex'
)
where identity_key is null or identity_key = '';

alter table public.tracked_students
    alter column identity_key set not null;

create unique index if not exists tracked_students_identity_key_unique
    on public.tracked_students (identity_key);

create index if not exists tracked_students_identity_idx
    on public.tracked_students (lower(name), lower(class_name), lower(email));

create table if not exists public.activity_link_activations (
    id bigint generated by default as identity primary key,
    student_id bigint references public.tracked_students(id) on delete set null,
    session_id text not null,
    public_link_code text not null,
    activated_at timestamptz not null default now(),
    ip_address text not null default '',
    user_agent text not null default '',
    device_type text not null default '',
    browser text not null default '',
    os text not null default '',
    is_mobile boolean not null default false
);

create index if not exists activity_link_activations_session_idx
    on public.activity_link_activations (session_id, activated_at desc);

create index if not exists activity_link_activations_student_idx
    on public.activity_link_activations (student_id, activated_at desc);

create table if not exists public.activity_test_sessions (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.tracked_students(id) on delete cascade,
    session_id text not null,
    test_id text not null,
    test_title text not null,
    started_at timestamptz not null default now(),
    last_activity_at timestamptz not null default now(),
    completed_at timestamptz,
    status text not null default 'started'
        check (status in ('started', 'in_progress', 'completed', 'abandoned')),
    score double precision,
    correct_answers integer,
    wrong_answers integer,
    total_questions integer,
    current_question_index integer not null default 0,
    answered_count integer not null default 0,
    progress_percent integer not null default 0
        check (progress_percent between 0 and 100)
);

create index if not exists activity_test_sessions_student_activity_idx
    on public.activity_test_sessions (student_id, last_activity_at desc);

create index if not exists activity_test_sessions_live_idx
    on public.activity_test_sessions (status, last_activity_at desc);

create table if not exists public.activity_events (
    id bigint generated by default as identity primary key,
    student_id bigint references public.tracked_students(id) on delete set null,
    session_id text not null,
    test_session_id bigint references public.activity_test_sessions(id) on delete cascade,
    event_type text not null,
    event_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists activity_events_created_idx
    on public.activity_events (created_at desc);

create index if not exists activity_events_student_created_idx
    on public.activity_events (student_id, created_at desc);

alter table public.app_settings enable row level security;
alter table public.auth_sessions enable row level security;
alter table public.learning_progress enable row level security;
alter table public.tracked_students enable row level security;
alter table public.activity_link_activations enable row level security;
alter table public.activity_test_sessions enable row level security;
alter table public.activity_events enable row level security;

-- Nu se definesc politici pentru anon/authenticated. Aceste tabele sunt accesate
-- exclusiv de backend prin SUPABASE_SERVICE_ROLE_KEY, care ocoleste RLS.
grant all on table public.app_settings to service_role;
grant all on table public.auth_sessions to service_role;
grant all on table public.learning_progress to service_role;
grant all on table public.tracked_students to service_role;
grant all on table public.activity_link_activations to service_role;
grant all on table public.activity_test_sessions to service_role;
grant all on table public.activity_events to service_role;

grant usage, select on all sequences in schema public to service_role;

-- Importul din SQLite pastreaza ID-urile vechi pentru a conserva relatiile.
-- Dupa import, secventele identity trebuie mutate dupa cel mai mare ID copiat.
create or replace function public.sync_legacy_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    target_sequence text;
    maximum_id bigint;
begin
    foreach target_sequence in array array[
        'learning_progress',
        'tracked_students',
        'activity_link_activations',
        'activity_test_sessions',
        'activity_events'
    ]
    loop
        execute format('select coalesce(max(id), 0) from public.%I', target_sequence)
            into maximum_id;
        if maximum_id = 0 then
            perform setval(
                pg_get_serial_sequence('public.' || target_sequence, 'id'),
                1,
                false
            );
        else
            perform setval(
                pg_get_serial_sequence('public.' || target_sequence, 'id'),
                maximum_id,
                true
            );
        end if;
    end loop;
end;
$$;

revoke all on function public.sync_legacy_identity_sequences() from public;
grant execute on function public.sync_legacy_identity_sequences() to service_role;
