export const samplePayload = {
  student_name: "da da",
  test_title: "Test de logica - 25 intrebari",
  attempt_id: "21B32DFBA9",
  submitted_at: "2026-04-19 11:20",
  duration_seconds: 42,
  admin_comment: "De revizuit partea definitiei si nevoia de identificare a clasificarilor.",
  categories: [
    { label: "Definitii", correct: 3, total: 5 },
    { label: "Clasificare", correct: 1, total: 5 },
    { label: "Propozitii categorice si distribuire", correct: 1, total: 5 },
    { label: "Rationamente si silogisme", correct: 0, total: 5 },
    { label: "Erori de rationament", correct: 0, total: 5 },
  ],
  questions: [
    {
      index: 1,
      lesson: "Definitii",
      question_text: "Omul este o fiinta rationala.",
      selected_answer: "Omul este o fiinta rationala.",
      correct_answer: "Omul este o fiinta rationala.",
      is_correct: true,
    },
    {
      index: 2,
      lesson: "Definitii",
      question_text: "Alege formularea corecta.",
      selected_answer: "Dreptul este un sistem de norme.",
      correct_answer: "Legea este ceea ce este legal.",
      is_correct: false,
    },
    {
      index: 3,
      lesson: "Clasificare",
      question_text: "Clasificarea trebuie sa respecte regula criteriului unic.",
      selected_answer: "Prea restransa",
      correct_answer: "Prea larga",
      is_correct: false,
    },
    {
      index: 4,
      lesson: "Propozitii categorice si distribuire",
      question_text: "Ce tip de propozitie este Toate persoanele sunt majore?",
      selected_answer: "A",
      correct_answer: "A",
      is_correct: true,
    },
  ],
}
